### ISSUE TITLE
Improve requirements.txt

### ISSUE THREAD

**Issue by rgaiacs** [okarras/EmpiRE-Analysis#2]
Relates to https://github.com/okarras/EmpiRE-Analysis/issues/1

Dear @okarras,

Can you change https://github.com/okarras/EmpiRE-Analysis/blob/2eb7478dba09a041e59e97abb5f8b00feaa7fd1d/requirements.txt to be deterministic by include the version? For example, replace `requirements.txt` with the output of `python3 -m pip freeze`.

cc @arnim

**Comment by okarras** [comment]
Done.
